---
# tasks file for webserver
- name: Install apache2
  ansible.builtin.apt:
    name: "{{ webserver }}"
    state: latest
  become: true

- name: Start service apache2, if not started
  ansible.builtin.service:
    name: apache2
    enabled: true
    state: started

- name: change owner and group for /var/www/html/index.html
  ansible.builtin.file:
    path: /var/www
    owner: ubuntu
    group: ubuntu
    recurse: true
    state: directory
  become: true

- name: delete index.html
  ansible.builtin.file:
    path: "{{ path }}/index.html"
    state: absent


- name: create index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: touch


- name: add a line to my index.html
  ansible.builtin.lineinfile:
    path: /var/www/html/index.html
    line: <h1>This is my website</h1>
  notify: Restart apache


- name: add users
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/bash
    groups: "{{ item.group }}"
  with_items:
    - name: bjgomes
      group: admin
    - name: ycasanova
      group: ubuntu
  become: true