{
    "_ansible_facts_gathered": true,
    "ansible_all_ipv4_addresses": [
        "10.36.0.0",
        "10.0.50.225"
    ],
    "ansible_all_ipv6_addresses": [
        "fe80::38d4:22ff:fe8b:6aeb",
        "fe80::685b:aff:fef8:3e78",
        "fe80::2419:17ff:fe58:b4c9",
        "fe80::c4bb:e2ff:fe3e:d57d",
        "fe80::8ff:e2ff:fe75:9edb",
        "fe80::9c8d:77ff:fee7:2390"
    ],
    "ansible_apparmor": {
        "status": "enabled"
    },
    "ansible_architecture": "x86_64",
    "ansible_bios_date": "10/16/2017",
    "ansible_bios_vendor": "Amazon EC2",
    "ansible_bios_version": "1.0",
    "ansible_board_asset_tag": "i-0ca2469ab057970b0",
    "ansible_board_name": "NA",
    "ansible_board_serial": "NA",
    "ansible_board_vendor": "Amazon EC2",
    "ansible_board_version": "NA",
    "ansible_chassis_asset_tag": "Amazon EC2",
    "ansible_chassis_serial": "NA",
    "ansible_chassis_vendor": "Amazon EC2",
    "ansible_chassis_version": "NA",
    "ansible_cmdline": {
        "BOOT_IMAGE": "/boot/vmlinuz-6.5.0-1014-aws",
        "console": "ttyS0",
        "nvme_core.io_timeout": "4294967295",
        "panic": "-1",
        "ro": true,
        "root": "PARTUUID=b4b91ea5-ac2a-4289-9a10-c53cba170810"
    },
    "ansible_datapath": {
        "active": true,
        "device": "datapath",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "on",
            "generic_segmentation_offload": "on",
            "highdma": "on",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "off [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "on [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "off [fixed]",
            "rx_all": "off [fixed]",
            "rx_checksumming": "off [fixed]",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "off [fixed]",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "off [fixed]",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "on",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "on",
            "tx_checksum_ipv4": "off [fixed]",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "off [fixed]",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "off [fixed]",
            "tx_fcoe_segmentation": "off [fixed]",
            "tx_gre_csum_segmentation": "on",
            "tx_gre_segmentation": "on",
            "tx_gso_list": "on",
            "tx_gso_partial": "off [fixed]",
            "tx_gso_robust": "off [fixed]",
            "tx_ipxip4_segmentation": "on",
            "tx_ipxip6_segmentation": "on",
            "tx_lockless": "on [fixed]",
            "tx_nocache_copy": "off",
            "tx_scatter_gather": "on",
            "tx_scatter_gather_fraglist": "on",
            "tx_sctp_segmentation": "on",
            "tx_tcp6_segmentation": "on",
            "tx_tcp_ecn_segmentation": "on",
            "tx_tcp_mangleid_segmentation": "on",
            "tx_tcp_segmentation": "on",
            "tx_tunnel_remcsum_segmentation": "off [fixed]",
            "tx_udp_segmentation": "on",
            "tx_udp_tnl_csum_segmentation": "on",
            "tx_udp_tnl_segmentation": "on",
            "tx_vlan_offload": "on",
            "tx_vlan_stag_hw_insert": "on",
            "vlan_challenged": "off [fixed]"
        },
        "hw_timestamp_filters": [],
        "ipv6": [
            {
                "address": "fe80::c4bb:e2ff:fe3e:d57d",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "c6:bb:e2:3e:d5:7d",
        "mtu": 1376,
        "promisc": true,
        "timestamping": [],
        "type": "ether"
    },
    "ansible_date_time": {
        "date": "2024-05-17",
        "day": "17",
        "epoch": "1715953136",
        "epoch_int": "1715953136",
        "hour": "13",
        "iso8601": "2024-05-17T13:38:56Z",
        "iso8601_basic": "20240517T133856038506",
        "iso8601_basic_short": "20240517T133856",
        "iso8601_micro": "2024-05-17T13:38:56.038506Z",
        "minute": "38",
        "month": "05",
        "second": "56",
        "time": "13:38:56",
        "tz": "UTC",
        "tz_dst": "UTC",
        "tz_offset": "+0000",
        "weekday": "Friday",
        "weekday_number": "5",
        "weeknumber": "20",
        "year": "2024"
    },
    "ansible_default_ipv4": {
        "address": "10.0.50.225",
        "alias": "ens5",
        "broadcast": "",
        "gateway": "10.0.50.1",
        "interface": "ens5",
        "macaddress": "0a:ff:e2:75:9e:db",
        "mtu": 9001,
        "netmask": "255.255.255.0",
        "network": "10.0.50.0",
        "prefix": "24",
        "type": "ether"
    },
    "ansible_default_ipv6": {},
    "ansible_device_links": {
        "ids": {
            "nvme0n1": [
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8",
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1",
                "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001"
            ],
            "nvme0n1p1": [
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8-part1",
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1-part1",
                "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part1"
            ],
            "nvme0n1p14": [
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8-part14",
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1-part14",
                "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part14"
            ],
            "nvme0n1p15": [
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8-part15",
                "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1-part15",
                "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part15"
            ]
        },
        "labels": {
            "nvme0n1p1": [
                "cloudimg-rootfs"
            ],
            "nvme0n1p15": [
                "UEFI"
            ]
        },
        "masters": {},
        "uuids": {
            "nvme0n1p1": [
                "f6fd4237-ee4f-48ac-a938-dbc9bcbc6a4a"
            ],
            "nvme0n1p15": [
                "916D-DEC3"
            ]
        }
    },
    "ansible_devices": {
        "loop0": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "113992",
            "sectorsize": "512",
            "size": "55.66 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop1": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "51000",
            "sectorsize": "512",
            "size": "24.90 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop2": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "130880",
            "sectorsize": "512",
            "size": "63.91 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop3": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "178152",
            "sectorsize": "512",
            "size": "86.99 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop4": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "82800",
            "sectorsize": "512",
            "size": "40.43 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop5": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "152040",
            "sectorsize": "512",
            "size": "74.24 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop6": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "36288",
            "sectorsize": "512",
            "size": "17.72 MB",
            "support_discard": "4096",
            "vendor": null,
            "virtual": 1
        },
        "loop7": {
            "holders": [],
            "host": "",
            "links": {
                "ids": [],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": null,
            "partitions": {},
            "removable": "0",
            "rotational": "1",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "0",
            "sectorsize": "512",
            "size": "0.00 Bytes",
            "support_discard": "0",
            "vendor": null,
            "virtual": 1
        },
        "nvme0n1": {
            "holders": [],
            "host": "Non-Volatile memory controller: Amazon.com, Inc. NVMe EBS Controller",
            "links": {
                "ids": [
                    "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8",
                    "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1",
                    "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001"
                ],
                "labels": [],
                "masters": [],
                "uuids": []
            },
            "model": "Amazon Elastic Block Store",
            "partitions": {
                "nvme0n1p1": {
                    "holders": [],
                    "links": {
                        "ids": [
                            "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8-part1",
                            "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1-part1",
                            "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part1"
                        ],
                        "labels": [
                            "cloudimg-rootfs"
                        ],
                        "masters": [],
                        "uuids": [
                            "f6fd4237-ee4f-48ac-a938-dbc9bcbc6a4a"
                        ]
                    },
                    "sectors": "16549855",
                    "sectorsize": 512,
                    "size": "7.89 GB",
                    "start": "227328",
                    "uuid": "f6fd4237-ee4f-48ac-a938-dbc9bcbc6a4a"
                },
                "nvme0n1p14": {
                    "holders": [],
                    "links": {
                        "ids": [
                            "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8-part14",
                            "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1-part14",
                            "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part14"
                        ],
                        "labels": [],
                        "masters": [],
                        "uuids": []
                    },
                    "sectors": "8192",
                    "sectorsize": 512,
                    "size": "4.00 MB",
                    "start": "2048",
                    "uuid": null
                },
                "nvme0n1p15": {
                    "holders": [],
                    "links": {
                        "ids": [
                            "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8-part15",
                            "nvme-Amazon_Elastic_Block_Store_vol01311509eeedc87b8_1-part15",
                            "nvme-nvme.1d0f-766f6c3031333131353039656565646338376238-416d617a6f6e20456c617374696320426c6f636b2053746f7265-00000001-part15"
                        ],
                        "labels": [
                            "UEFI"
                        ],
                        "masters": [],
                        "uuids": [
                            "916D-DEC3"
                        ]
                    },
                    "sectors": "217088",
                    "sectorsize": 512,
                    "size": "106.00 MB",
                    "start": "10240",
                    "uuid": "916D-DEC3"
                }
            },
            "removable": "0",
            "rotational": "0",
            "sas_address": null,
            "sas_device_handle": null,
            "scheduler_mode": "none",
            "sectors": "16777216",
            "sectorsize": "512",
            "size": "8.00 GB",
            "support_discard": "0",
            "vendor": null,
            "virtual": 1
        }
    },
    "ansible_distribution": "Ubuntu",
    "ansible_distribution_file_parsed": true,
    "ansible_distribution_file_path": "/etc/os-release",
    "ansible_distribution_file_variety": "Debian",
    "ansible_distribution_major_version": "22",
    "ansible_distribution_release": "jammy",
    "ansible_distribution_version": "22.04",
    "ansible_dns": {
        "nameservers": [
            "127.0.0.53"
        ],
        "options": {
            "edns0": true,
            "trust-ad": true
        },
        "search": [
            "ec2.internal"
        ]
    },
    "ansible_domain": "superman",
    "ansible_effective_group_id": 1000,
    "ansible_effective_user_id": 1000,
    "ansible_ens5": {
        "active": true,
        "device": "ens5",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "on",
            "generic_segmentation_offload": "on",
            "highdma": "on",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "off [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "off [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "on",
            "rx_all": "off [fixed]",
            "rx_checksumming": "off [fixed]",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "off [fixed]",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "off [fixed]",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "off",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "off [fixed]",
            "tx_checksum_ipv4": "on",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "off [fixed]",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "off [fixed]",
            "tx_fcoe_segmentation": "off [fixed]",
            "tx_gre_csum_segmentation": "off [fixed]",
            "tx_gre_segmentation": "off [fixed]",
            "tx_gso_list": "off [fixed]",
            "tx_gso_partial": "off [fixed]",
            "tx_gso_robust": "off [fixed]",
            "tx_ipxip4_segmentation": "off [fixed]",
            "tx_ipxip6_segmentation": "off [fixed]",
            "tx_lockless": "off [fixed]",
            "tx_nocache_copy": "off",
            "tx_scatter_gather": "on",
            "tx_scatter_gather_fraglist": "off [fixed]",
            "tx_sctp_segmentation": "off [fixed]",
            "tx_tcp6_segmentation": "off [fixed]",
            "tx_tcp_ecn_segmentation": "off [fixed]",
            "tx_tcp_mangleid_segmentation": "off [fixed]",
            "tx_tcp_segmentation": "off [fixed]",
            "tx_tunnel_remcsum_segmentation": "off [fixed]",
            "tx_udp_segmentation": "off [fixed]",
            "tx_udp_tnl_csum_segmentation": "off [fixed]",
            "tx_udp_tnl_segmentation": "off [fixed]",
            "tx_vlan_offload": "off [fixed]",
            "tx_vlan_stag_hw_insert": "off [fixed]",
            "vlan_challenged": "off [fixed]"
        },
        "hw_timestamp_filters": [],
        "ipv4": {
            "address": "10.0.50.225",
            "broadcast": "",
            "netmask": "255.255.255.0",
            "network": "10.0.50.0",
            "prefix": "24"
        },
        "ipv6": [
            {
                "address": "fe80::8ff:e2ff:fe75:9edb",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "0a:ff:e2:75:9e:db",
        "module": "ena",
        "mtu": 9001,
        "pciid": "0000:00:05.0",
        "promisc": false,
        "timestamping": [],
        "type": "ether"
    },
    "ansible_env": {
        "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
        "HOME": "/home/ubuntu",
        "LANG": "C.UTF-8",
        "LOGNAME": "ubuntu",
        "MOTD_SHOWN": "pam",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
        "PRIMARY_IP": "34.229.174.194",
        "PWD": "/home/ubuntu",
        "SHELL": "/bin/bash",
        "SHLVL": "0",
        "SSH_CLIENT": "10.0.50.111 59518 22",
        "SSH_CONNECTION": "10.0.50.111 59518 10.0.50.225 22",
        "SSH_TTY": "/dev/pts/0",
        "TERM": "xterm-256color",
        "USER": "ubuntu",
        "XDG_RUNTIME_DIR": "/run/user/1000",
        "XDG_SESSION_CLASS": "user",
        "XDG_SESSION_ID": "4",
        "XDG_SESSION_TYPE": "tty",
        "_": "/bin/sh"
    },
    "ansible_fibre_channel_wwn": [],
    "ansible_fips": false,
    "ansible_form_factor": "Other",
    "ansible_fqdn": "skillstormprep.superman",
    "ansible_hostname": "node01",
    "ansible_hostnqn": "",
    "ansible_interfaces": [
        "vethwe-datapath",
        "weave",
        "vxlan-6784",
        "ens5",
        "datapath",
        "lo",
        "vethwe-bridge"
    ],
    "ansible_is_chroot": false,
    "ansible_iscsi_iqn": "",
    "ansible_kernel": "6.5.0-1014-aws",
    "ansible_kernel_version": "#14~22.04.1-Ubuntu SMP Thu Feb 15 15:27:06 UTC 2024",
    "ansible_lo": {
        "active": true,
        "device": "lo",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "on",
            "generic_segmentation_offload": "on",
            "highdma": "on [fixed]",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "on [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "on [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "off [fixed]",
            "rx_all": "off [fixed]",
            "rx_checksumming": "on [fixed]",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "off [fixed]",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "off [fixed]",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "on",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "on [fixed]",
            "tx_checksum_ipv4": "off [fixed]",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "on [fixed]",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "off [fixed]",
            "tx_fcoe_segmentation": "off [fixed]",
            "tx_gre_csum_segmentation": "off [fixed]",
            "tx_gre_segmentation": "off [fixed]",
            "tx_gso_list": "on",
            "tx_gso_partial": "off [fixed]",
            "tx_gso_robust": "off [fixed]",
            "tx_ipxip4_segmentation": "off [fixed]",
            "tx_ipxip6_segmentation": "off [fixed]",
            "tx_lockless": "on [fixed]",
            "tx_nocache_copy": "off [fixed]",
            "tx_scatter_gather": "on [fixed]",
            "tx_scatter_gather_fraglist": "on [fixed]",
            "tx_sctp_segmentation": "on",
            "tx_tcp6_segmentation": "on",
            "tx_tcp_ecn_segmentation": "on",
            "tx_tcp_mangleid_segmentation": "on",
            "tx_tcp_segmentation": "on",
            "tx_tunnel_remcsum_segmentation": "off [fixed]",
            "tx_udp_segmentation": "on",
            "tx_udp_tnl_csum_segmentation": "off [fixed]",
            "tx_udp_tnl_segmentation": "off [fixed]",
            "tx_vlan_offload": "off [fixed]",
            "tx_vlan_stag_hw_insert": "off [fixed]",
            "vlan_challenged": "on [fixed]"
        },
        "hw_timestamp_filters": [],
        "ipv4": {
            "address": "127.0.0.1",
            "broadcast": "",
            "netmask": "255.0.0.0",
            "network": "127.0.0.0",
            "prefix": "8"
        },
        "ipv6": [
            {
                "address": "::1",
                "prefix": "128",
                "scope": "host"
            }
        ],
        "mtu": 65536,
        "promisc": false,
        "timestamping": [],
        "type": "loopback"
    },
    "ansible_loadavg": {
        "15m": 0.26123046875,
        "1m": 0.0,
        "5m": 0.1337890625
    },
    "ansible_local": {},
    "ansible_locally_reachable_ips": {
        "ipv4": [
            "10.0.50.225",
            "10.36.0.0",
            "127.0.0.0/8",
            "127.0.0.1"
        ],
        "ipv6": [
            "::1",
            "fe80::8ff:e2ff:fe75:9edb",
            "fe80::2419:17ff:fe58:b4c9",
            "fe80::38d4:22ff:fe8b:6aeb",
            "fe80::685b:aff:fef8:3e78",
            "fe80::9c8d:77ff:fee7:2390",
            "fe80::c4bb:e2ff:fe3e:d57d"
        ]
    },
    "ansible_lsb": {
        "codename": "jammy",
        "description": "Ubuntu 22.04.4 LTS",
        "id": "Ubuntu",
        "major_release": "22",
        "release": "22.04"
    },
    "ansible_lvm": "N/A",
    "ansible_machine": "x86_64",
    "ansible_machine_id": "ec2e522de3430162ac3199f6e31bbc65",
    "ansible_memfree_mb": 255,
    "ansible_memory_mb": {
        "nocache": {
            "free": 3168,
            "used": 659
        },
        "real": {
            "free": 255,
            "total": 3827,
            "used": 3572
        },
        "swap": {
            "cached": 0,
            "free": 0,
            "total": 0,
            "used": 0
        }
    },
    "ansible_memtotal_mb": 3827,
    "ansible_mounts": [
        {
            "block_available": 820332,
            "block_size": 4096,
            "block_total": 1985394,
            "block_used": 1165062,
            "device": "/dev/root",
            "fstype": "ext4",
            "inode_available": 839913,
            "inode_total": 1032192,
            "inode_used": 192279,
            "mount": "/",
            "options": "rw,relatime,discard,errors=remount-ro",
            "size_available": 3360079872,
            "size_total": 8132173824,
            "uuid": "f6fd4237-ee4f-48ac-a938-dbc9bcbc6a4a"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 200,
            "block_used": 200,
            "device": "/dev/loop1",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 16,
            "inode_used": 16,
            "mount": "/snap/amazon-ssm-agent/7628",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 26214400,
            "uuid": "N/A"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 446,
            "block_used": 446,
            "device": "/dev/loop0",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 10944,
            "inode_used": 10944,
            "mount": "/snap/core18/2812",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 58458112,
            "uuid": "N/A"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 512,
            "block_used": 512,
            "device": "/dev/loop2",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 12041,
            "inode_used": 12041,
            "mount": "/snap/core20/2182",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 67108864,
            "uuid": "N/A"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 696,
            "block_used": 696,
            "device": "/dev/loop3",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 959,
            "inode_used": 959,
            "mount": "/snap/lxd/27037",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 91226112,
            "uuid": "N/A"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 324,
            "block_used": 324,
            "device": "/dev/loop4",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 658,
            "inode_used": 658,
            "mount": "/snap/snapd/20671",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 42467328,
            "uuid": "N/A"
        },
        {
            "block_available": 201292,
            "block_size": 512,
            "block_total": 213663,
            "block_used": 12371,
            "device": "/dev/nvme0n1p15",
            "fstype": "vfat",
            "inode_available": 0,
            "inode_total": 0,
            "inode_used": 0,
            "mount": "/boot/efi",
            "options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro",
            "size_available": 103061504,
            "size_total": 109395456,
            "uuid": "916D-DEC3"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 594,
            "block_used": 594,
            "device": "/dev/loop5",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 14458,
            "inode_used": 14458,
            "mount": "/snap/core22/1380",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 77856768,
            "uuid": "N/A"
        },
        {
            "block_available": 0,
            "block_size": 131072,
            "block_total": 142,
            "block_used": 142,
            "device": "/dev/loop6",
            "fstype": "squashfs",
            "inode_available": 0,
            "inode_total": 12,
            "inode_used": 12,
            "mount": "/snap/helm/406",
            "options": "ro,nodev,relatime,errors=continue,threads=single",
            "size_available": 0,
            "size_total": 18612224,
            "uuid": "N/A"
        }
    ],
    "ansible_nodename": "node01",
    "ansible_os_family": "Debian",
    "ansible_pkg_mgr": "apt",
    "ansible_proc_cmdline": {
        "BOOT_IMAGE": "/boot/vmlinuz-6.5.0-1014-aws",
        "console": [
            "tty1",
            "ttyS0"
        ],
        "nvme_core.io_timeout": "4294967295",
        "panic": "-1",
        "ro": true,
        "root": "PARTUUID=b4b91ea5-ac2a-4289-9a10-c53cba170810"
    },
    "ansible_processor": [
        "0",
        "GenuineIntel",
        "Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz",
        "1",
        "GenuineIntel",
        "Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz"
    ],
    "ansible_processor_cores": 1,
    "ansible_processor_count": 1,
    "ansible_processor_nproc": 2,
    "ansible_processor_threads_per_core": 2,
    "ansible_processor_vcpus": 2,
    "ansible_product_name": "t3.medium",
    "ansible_product_serial": "NA",
    "ansible_product_uuid": "NA",
    "ansible_product_version": "NA",
    "ansible_python": {
        "executable": "/usr/bin/python3",
        "has_sslcontext": true,
        "type": "cpython",
        "version": {
            "major": 3,
            "micro": 12,
            "minor": 10,
            "releaselevel": "final",
            "serial": 0
        },
        "version_info": [
            3,
            10,
            12,
            "final",
            0
        ]
    },
    "ansible_python_version": "3.10.12",
    "ansible_real_group_id": 1000,
    "ansible_real_user_id": 1000,
    "ansible_selinux": {
        "status": "disabled"
    },
    "ansible_selinux_python_present": true,
    "ansible_service_mgr": "systemd",
    "ansible_ssh_host_key_dsa_public": "AAAAB3NzaC1kc3MAAACBAM79jr7/ZXtyoypcBsbloyx1XvurNdR4KXMqImOL0kC9tuUpjJVXnSh8WeW0Sf9+L4dIGo7SB+spEuWX8BIy4z7yVy93Ku4UNlLBrAPj6QycJO7Ag86n/32BXgkp7vcVoH1yl6EiUhbXsooYZ/EzNIa0J8P9oOZ4SY26oVt4trFZAAAAFQCTcEW5ciEZQZzTRtWPLQfYhQq0zwAAAIBbJllRlodudBUBVawlY+NrTs8AptaS7exUNECszrPaPu4elovDv57i4DwqF/8INEoO3OCCOsUePACHmSYCJQDaKB6ZHFzhXwpchAsQ0iyDJ6YlNQ/0up4R0kGVtladZGVPsn6ijJ+2GAObIq90ckyWq4B4MNOx9J/Grtf3ZWgkTwAAAIAlacT8VhKiTtM75SJPht2tzkR59KtWbBdxHnwEtHQOFIuHSMfmfhLXCwja//l38nOPX9G2Y2D2K8p0POp4jLr2/LNLMX1xoV9aQ0CHwGfxON0bCqjvU/MUFWtudJAvSCe+WNFNi8/UzGlSJE4DrH9cNZFz3h+bi7xrB/EwPKGkAQ==",
    "ansible_ssh_host_key_dsa_public_keytype": "ssh-dss",
    "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLxtb7xaebYny3+WKTZtSm33omnivvQMe7fcm4Z4vXnoWrTBQW27XZNG8vjyRHRsFcwsPEbkNubZxlBpEptepX0=",
    "ansible_ssh_host_key_ecdsa_public_keytype": "ecdsa-sha2-nistp256",
    "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAIFoMkvy+P8nvK5uvrVNNcNyp4hXgON3UlGICscLYqo7n",
    "ansible_ssh_host_key_ed25519_public_keytype": "ssh-ed25519",
    "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABgQClRTRqA5Ox7Y5JFJzyjD1P2yL/gRUyfIx+Uibx6Zof1jhp8qQjj9v8tMXuNtL94ED0fwDAYhHvjREjpfP6cJmUP5jh73bK3I+djhlFUDsup0MP1QsXOaASKU2m1mc/0G6U0dXifdCsWM5p1l//LH0Lyd9TgYTsCW7oaPt8DiEdKRQ8ZzUqAnqDB7k4iqHFsNjgCEnr1B155FuOdQMpmBdL0b97fyYElsd8LzG5Wy32oVBGjtldkISyhk4es2zSWVvwiqXb0gdolI36oFSD5oQCjNx0hH6Zk5Wbz41DmvznAcANiLh5k716LQYZX8f5alWrNkBrAHOaydbjH5CnZCOXs0U/RXrDe6Z1LztjyUSRew3kZF4Y9SUAgc/fmSoabGMmebakjlVqLyfUwVS54FX0uHOo3dMnwANs2fyipU5z3LFsr/K2DQxMNEaO5/SNp+GPO9cvKd8gVHFZfKslxHHi+xthUSJRLy+G1wXxmgtgF5ru07ksCKsrH1F2bDqN370=",
    "ansible_ssh_host_key_rsa_public_keytype": "ssh-rsa",
    "ansible_swapfree_mb": 0,
    "ansible_swaptotal_mb": 0,
    "ansible_system": "Linux",
    "ansible_system_capabilities": [
        ""
    ],
    "ansible_system_capabilities_enforced": "True",
    "ansible_system_vendor": "Amazon EC2",
    "ansible_uptime_seconds": 1133,
    "ansible_user_dir": "/home/ubuntu",
    "ansible_user_gecos": "Ubuntu",
    "ansible_user_gid": 1000,
    "ansible_user_id": "ubuntu",
    "ansible_user_shell": "/bin/bash",
    "ansible_user_uid": 1000,
    "ansible_userspace_architecture": "x86_64",
    "ansible_userspace_bits": "64",
    "ansible_vethwe_bridge": {
        "active": true,
        "device": "vethwe-bridge",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "off",
            "generic_segmentation_offload": "on",
            "highdma": "on",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "off [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "off [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "off [fixed]",
            "rx_all": "off [fixed]",
            "rx_checksumming": "on",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "on",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "on",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "on",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "on",
            "tx_checksum_ipv4": "off [fixed]",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "on",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "off [fixed]",
            "tx_fcoe_segmentation": "off [fixed]",
            "tx_gre_csum_segmentation": "on",
            "tx_gre_segmentation": "on",
            "tx_gso_list": "on",
            "tx_gso_partial": "off [fixed]",
            "tx_gso_robust": "off [fixed]",
            "tx_ipxip4_segmentation": "on",
            "tx_ipxip6_segmentation": "on",
            "tx_lockless": "on [fixed]",
            "tx_nocache_copy": "off",
            "tx_scatter_gather": "on",
            "tx_scatter_gather_fraglist": "on",
            "tx_sctp_segmentation": "on",
            "tx_tcp6_segmentation": "on",
            "tx_tcp_ecn_segmentation": "on",
            "tx_tcp_mangleid_segmentation": "on",
            "tx_tcp_segmentation": "on",
            "tx_tunnel_remcsum_segmentation": "off [fixed]",
            "tx_udp_segmentation": "on",
            "tx_udp_tnl_csum_segmentation": "on",
            "tx_udp_tnl_segmentation": "on",
            "tx_vlan_offload": "on",
            "tx_vlan_stag_hw_insert": "on",
            "vlan_challenged": "off [fixed]"
        },
        "hw_timestamp_filters": [],
        "ipv6": [
            {
                "address": "fe80::38d4:22ff:fe8b:6aeb",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "2e:26:dc:85:78:21",
        "mtu": 1376,
        "promisc": true,
        "speed": 10000,
        "timestamping": [],
        "type": "ether"
    },
    "ansible_vethwe_datapath": {
        "active": true,
        "device": "vethwe-datapath",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "off",
            "generic_segmentation_offload": "on",
            "highdma": "on",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "off [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "off [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "off [fixed]",
            "rx_all": "off [fixed]",
            "rx_checksumming": "on",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "on",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "on",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "on",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "on",
            "tx_checksum_ipv4": "off [fixed]",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "on",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "off [fixed]",
            "tx_fcoe_segmentation": "off [fixed]",
            "tx_gre_csum_segmentation": "on",
            "tx_gre_segmentation": "on",
            "tx_gso_list": "on",
            "tx_gso_partial": "off [fixed]",
            "tx_gso_robust": "off [fixed]",
            "tx_ipxip4_segmentation": "on",
            "tx_ipxip6_segmentation": "on",
            "tx_lockless": "on [fixed]",
            "tx_nocache_copy": "off",
            "tx_scatter_gather": "on",
            "tx_scatter_gather_fraglist": "on",
            "tx_sctp_segmentation": "on",
            "tx_tcp6_segmentation": "on",
            "tx_tcp_ecn_segmentation": "on",
            "tx_tcp_mangleid_segmentation": "on",
            "tx_tcp_segmentation": "on",
            "tx_tunnel_remcsum_segmentation": "off [fixed]",
            "tx_udp_segmentation": "on",
            "tx_udp_tnl_csum_segmentation": "on",
            "tx_udp_tnl_segmentation": "on",
            "tx_vlan_offload": "on",
            "tx_vlan_stag_hw_insert": "on",
            "vlan_challenged": "off [fixed]"
        },
        "hw_timestamp_filters": [],
        "ipv6": [
            {
                "address": "fe80::9c8d:77ff:fee7:2390",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "d6:70:d5:59:22:35",
        "mtu": 1376,
        "promisc": true,
        "speed": 10000,
        "timestamping": [],
        "type": "ether"
    },
    "ansible_virtualization_role": "guest",
    "ansible_virtualization_tech_guest": [
        "kvm"
    ],
    "ansible_virtualization_tech_host": [],
    "ansible_virtualization_type": "kvm",
    "ansible_vxlan_6784": {
        "active": true,
        "device": "vxlan-6784",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "on",
            "generic_segmentation_offload": "on",
            "highdma": "off [fixed]",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "off [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "off [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "off [fixed]",
            "rx_all": "off [fixed]",
            "rx_checksumming": "on",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "off [fixed]",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "off [fixed]",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "on",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "on",
            "tx_checksum_ipv4": "off [fixed]",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "off [fixed]",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "off [fixed]",
            "tx_fcoe_segmentation": "off [fixed]",
            "tx_gre_csum_segmentation": "off [fixed]",
            "tx_gre_segmentation": "off [fixed]",
            "tx_gso_list": "on",
            "tx_gso_partial": "off [fixed]",
            "tx_gso_robust": "off [fixed]",
            "tx_ipxip4_segmentation": "off [fixed]",
            "tx_ipxip6_segmentation": "off [fixed]",
            "tx_lockless": "on [fixed]",
            "tx_nocache_copy": "off",
            "tx_scatter_gather": "on",
            "tx_scatter_gather_fraglist": "on",
            "tx_sctp_segmentation": "on",
            "tx_tcp6_segmentation": "on",
            "tx_tcp_ecn_segmentation": "on",
            "tx_tcp_mangleid_segmentation": "on",
            "tx_tcp_segmentation": "on",
            "tx_tunnel_remcsum_segmentation": "off [fixed]",
            "tx_udp_segmentation": "on",
            "tx_udp_tnl_csum_segmentation": "off [fixed]",
            "tx_udp_tnl_segmentation": "off [fixed]",
            "tx_vlan_offload": "off [fixed]",
            "tx_vlan_stag_hw_insert": "off [fixed]",
            "vlan_challenged": "off [fixed]"
        },
        "hw_timestamp_filters": [],
        "ipv6": [
            {
                "address": "fe80::685b:aff:fef8:3e78",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "76:2d:e0:2f:6b:ca",
        "mtu": 65535,
        "promisc": true,
        "speed": -1,
        "timestamping": [],
        "type": "ether"
    },
    "ansible_weave": {
        "active": true,
        "device": "weave",
        "features": {
            "esp_hw_offload": "off [fixed]",
            "esp_tx_csum_hw_offload": "off [fixed]",
            "fcoe_mtu": "off [fixed]",
            "generic_receive_offload": "on",
            "generic_segmentation_offload": "on",
            "highdma": "on",
            "hsr_dup_offload": "off [fixed]",
            "hsr_fwd_offload": "off [fixed]",
            "hsr_tag_ins_offload": "off [fixed]",
            "hsr_tag_rm_offload": "off [fixed]",
            "hw_tc_offload": "off [fixed]",
            "l2_fwd_offload": "off [fixed]",
            "large_receive_offload": "off [fixed]",
            "loopback": "off [fixed]",
            "macsec_hw_offload": "off [fixed]",
            "netns_local": "on [fixed]",
            "ntuple_filters": "off [fixed]",
            "receive_hashing": "off [fixed]",
            "rx_all": "off [fixed]",
            "rx_checksumming": "off [fixed]",
            "rx_fcs": "off [fixed]",
            "rx_gro_hw": "off [fixed]",
            "rx_gro_list": "off",
            "rx_udp_gro_forwarding": "off",
            "rx_udp_tunnel_port_offload": "off [fixed]",
            "rx_vlan_filter": "off [fixed]",
            "rx_vlan_offload": "off [fixed]",
            "rx_vlan_stag_filter": "off [fixed]",
            "rx_vlan_stag_hw_parse": "off [fixed]",
            "scatter_gather": "on",
            "tcp_segmentation_offload": "on",
            "tls_hw_record": "off [fixed]",
            "tls_hw_rx_offload": "off [fixed]",
            "tls_hw_tx_offload": "off [fixed]",
            "tx_checksum_fcoe_crc": "off [fixed]",
            "tx_checksum_ip_generic": "on",
            "tx_checksum_ipv4": "off [fixed]",
            "tx_checksum_ipv6": "off [fixed]",
            "tx_checksum_sctp": "off [fixed]",
            "tx_checksumming": "on",
            "tx_esp_segmentation": "on",
            "tx_fcoe_segmentation": "off [requested on]",
            "tx_gre_csum_segmentation": "on",
            "tx_gre_segmentation": "on",
            "tx_gso_list": "on",
            "tx_gso_partial": "on",
            "tx_gso_robust": "off [requested on]",
            "tx_ipxip4_segmentation": "on",
            "tx_ipxip6_segmentation": "on",
            "tx_lockless": "on [fixed]",
            "tx_nocache_copy": "off",
            "tx_scatter_gather": "on",
            "tx_scatter_gather_fraglist": "on",
            "tx_sctp_segmentation": "on",
            "tx_tcp6_segmentation": "on",
            "tx_tcp_ecn_segmentation": "on",
            "tx_tcp_mangleid_segmentation": "on",
            "tx_tcp_segmentation": "on",
            "tx_tunnel_remcsum_segmentation": "on",
            "tx_udp_segmentation": "on",
            "tx_udp_tnl_csum_segmentation": "on",
            "tx_udp_tnl_segmentation": "on",
            "tx_vlan_offload": "on",
            "tx_vlan_stag_hw_insert": "on",
            "vlan_challenged": "off [fixed]"
        },
        "hw_timestamp_filters": [],
        "id": "8000.26191758b4c9",
        "interfaces": [
            "vethwe-bridge"
        ],
        "ipv4": {
            "address": "10.36.0.0",
            "broadcast": "10.47.255.255",
            "netmask": "255.240.0.0",
            "network": "10.32.0.0",
            "prefix": "12"
        },
        "ipv6": [
            {
                "address": "fe80::2419:17ff:fe58:b4c9",
                "prefix": "64",
                "scope": "link"
            }
        ],
        "macaddress": "26:19:17:58:b4:c9",
        "mtu": 1376,
        "promisc": false,
        "speed": 10000,
        "stp": false,
        "timestamping": [],
        "type": "bridge"
    },
    "discovered_interpreter_python": "/usr/bin/python3",
    "gather_subset": [
        "all"
    ],
    "module_setup": true
}